<?php

namespace App\Controllers\User;

use App\Controllers\BaseController;
use App\Models\Article;
use CodeIgniter\Files\File;
use CodeIgniter\Files\FileCollection;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Panel extends BaseController
{
    public ?array $articles = null;
    public ?string $locale = null;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->articles = model('Article')->where('user_id',service('auth')->user()->id)->findAll();
        $this ->locale = setting()->get('App.defaultLocale','locale');
        service('language')->setLocale($this->locale);
    }

    public function index()
    {
        return view('panel/user/dashboard_'.$this->locale,['articles' => $this->articles]);
    }

    public function delete($id)
    {
        if($this->request->isAJAX()) {
//            if (service('auth')->user()->can('users.delete')) {
                service('auth')->getProvider()->delete($id);
                return $this->response->setJSON(['success' => true]);
//            }
        }
    }
}
