<?php

namespace App\Controllers;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Home extends BaseController
{
    public ?string $locale = null;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this ->locale = setting()->get('App.defaultLocale','locale');
        service('language')->setLocale($this->locale);
    }

    public function index(): string
    {
        return view('home_'.$this ->locale);
    }
}
