<?php

namespace App\Controllers;

use App\Controllers\BaseController;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Language extends BaseController
{
    public ?string $locale = null;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->locale = $this->request->getLocale();
    }

    public function index()
    {
        setting()->set('App.defaultLocale', $this->locale);

        return redirect()->to($_SERVER['HTTP_REFERER']);
    }
}
